apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - "server"
            - "/data"
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_BROWSER
              value: "off"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: password
