apiVersion: v2
name: picturas-chart
description: A Helm chart for deploying Picturas in Kubernetes

type: application
version: 0.0.1
appVersion: "latest"

dependencies:
  - name: rabbitmq
    version: 15.2.1
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 20.6.1
    repository: https://charts.bitnami.com/bitnami
    alias: rate-limiter-redis
  - name: redis
    version: 20.6.1
    repository: https://charts.bitnami.com/bitnami
    alias: ws-redis
  - name: redis
    version: 20.6.1
    repository: https://charts.bitnami.com/bitnami
    alias: filter-redis
  - name: mongodb
    version: 16.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: users-ms-db
  - name: mongodb
    version: 16.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: projects-ms-db
  - name: mongodb
    version: 16.4.0
    repository: https://charts.bitnami.com/bitnami
    alias: subscriptions-ms-db
  - name: minio
    version: 14.10.3
    repository: https://charts.bitnami.com/bitnami
  # Monitoring
  - name: kube-prometheus
    version: 10.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: production.enabled
  - name: grafana
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: production.enabled
  - name: grafana-loki
    version: 4.7.1
    repository: https://charts.bitnami.com/bitnami
    condition: production.enabled
  # TODO Thanos + Grafana Mimir
