{{- if .Values.production.enabled }}
{{- range .Values.filters }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ . }}
  minReplicas: {{ $.Values.production.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.production.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.production.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.production.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.production.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.production.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
