apiVersion: v1
kind: Service
metadata:
  name: api-gateway-metrics
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
  selector:
    name: api-gateway
