apiVersion: v1
kind: Service
metadata:
  name: ws-gateway-metrics
  labels:
    app: ws-gateway
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9113
  selector:
    name: ws-gateway
