{{- if .Values.production.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ws-gateway
spec:
  endpoints:
    - port: http-metrics
      interval: 30s
  selector:
    matchLabels:
      app: ws-gateway
{{- end }}
