apiVersion: v1
kind: Service
metadata:
  name: web-metrics
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
  selector:
    name: web
