{{- if .Values.production.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
spec:
  endpoints:
    - port: http-metrics
      interval: 30s
  selector:
    matchLabels:
      name: web-metrics
{{- end }}
