apiVersion: v1
kind: Service
metadata:
  name: subscriptions-ms-metrics
  labels:
    app: subscriptions-ms
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
  selector:
    name: subscriptions-ms
